### ISSUE TITLE
[Bug]: Mac M1 docker image not available

### ISSUE THREAD

**Issue by Nesqwik** [lenra-io/server#366]
### What happened?

When i try to pull the lenra/server:beta, i got an error.
The Mac M1 ARM64 image does not seems to exists. 

### What browsers are you seeing the problem on?

Other (specify above)

### Version

beta

### Relevant log output

```Shell
❯ docker pull lenra/server:beta
beta: Pulling from lenra/server
no matching manifest for linux/arm64/v8 in the manifest list entries
```

**Comment by taorepoara** [comment]
Since we do not have Mac M1 servers this target architecture is not in our priority.

**Comment by Nesqwik** [comment]
It should not take long to add the Mac M1 support and help a lot for developers with an M1 chip. We should consider adding the support !
