### ISSUE TITLE
[Task] Create the Login HTML page and redirection flow

### ISSUE THREAD

**Issue by Nesqwik** [lenra-io/server#372]
Create the Login HTML page and implement the redirection flow.
Very similar to https://github.com/lenra-io/server/issues/370 but simpler since it's only for the login.

See the [Notion Guide](https://rattle-llama-7da.notion.site/OAuth-Provider-c43ec6d6f23e47c6939166c3d594d698#28d344eacbbc4d1fa2a5f182e1ac4891) for this part. 

Basically you : 
- Get the Login redirection from Hydra with a login_challenge (a code)
- Get the Login data to Hydra using the login_challenge
- According to the Login data, we can show the login page.
- The user login and submit the form to us
- We use the form to check the credentials and accept/deny the login to hydra and redirect the user.

**Comment by taorepoara** [comment]
Actually we a single page for register and login, but there is two different design for them:
- one for the dev backoffice
- one for all other cases (for now, using an app).

See: https://www.figma.com/file/1TeGq312pT4ZIiRn5u6iYU/03_ipsoon%26lesdevs?node-id=1093%3A14625&t=hwZEP62cU3E0z3w1-1
