### ISSUE TITLE
[Task] Add the Lenra OAuth Client in a migration

### ISSUE THREAD

**Issue by Nesqwik** [lenra-io/server#375]
There is an Hydra API endpoint to create the Lenra OAuth client.
Creating the "client" in the back-end is mandatory for the Lenra Client or any other third client to use the OAuth Endpoint.

See [Hydra API Doc](https://www.ory.sh/docs/hydra/reference/api#tag/oAuth2/operation/createOAuth2Client)

This PR must ensure that the Client will be created correctly before starting the Identity endpoint. This "migration" must be idempotent.
This is not a database migration but more like a mandatory idempotent HTTP request.

**Comment by Nesqwik** [comment]
Ok so the main issue i'm currently facing is that we cannot create a new OAuth Client on ORY Hydra with a predefined client_id. The client_id is always generated by Hydra.

This means that we cannot create a "migration" that create a pre-determined client for the OAuth system.

The solutions : 
- We manually create the client on Hydra once then manually update the client source code to use this generated OAuth client_id.
- We create the OAuth client once during the "migration" then we store the client_id somewhere. The client app use an API that returns the created client_id.
-

**Comment by taorepoara** [comment]
Can't we specify metadata in the Hydra client to look for it in the migration and create it if it doesn't exist ?
The clients (client and backoffice) will be displayed in the server logs to make them easy to use for local development.

**Comment by Nesqwik** [comment]
> Can't we specify metadata in the Hydra client to look for it in the migration and create it if it doesn't exist ? 

Technically possible but it will be awful when hundred/thousands of oauth client will spawn on production. This means everytime the server starts, we will get ALL the oauth clients, check their metadata and then create them if they're not already created.

In development only, this could be a possible solution tho.
