### ISSUE TITLE
[Task] Add a setting to add/update the Lenra App OAuth Client

### ISSUE THREAD

**Issue by Nesqwik** [lenra-io/server#378]
When creating a Lenra App using a third client, the developper will need to login the user using the new OAuth system.
To do this, he need to create a "OAuth client" for his application. 

What need to be done :
- List the features that need to be present in the UI 
- Create the design for the UI
- Implement the back-end features
- Implement the front-end features

See the Google console interface to create the OAuth client for more informations.

⚠️ After discussion, please create the client part of this task and link it here ! ⚠️

**Comment by jonas-martinez** [comment]
The google oauth client creation first step is to choose the platform for the client. Do we want to use the same principle on Lenra? We could skip this step and just make a oauth client compatible with all platforms but it seems that this is not recommended as it can make it less secure. 

Should we select the platform at the creation of a oauth client on the backoffice or just make it compatible with all platforms ?

**Comment by jonas-martinez** [comment]
After some discussions with @taorepoara, we will follow the security guidelines for oauth and make the developer choose the platform (windows, linux, web, android, mac, ios, ...) when creating a oauth client in the backoffice.
