### ISSUE TITLE
[Bug]: Login page warning Icons are not loading

### ISSUE THREAD

**Issue by Nesqwik** [lenra-io/server#419]
### What happened?

The error (red) icons are not loading in the register page. (https://account.staging.lenra.io/users/register)
![Capture d’écran 2023-09-06 à 12 07 17](https://github.com/lenra-io/server/assets/6428498/334a8a7a-40e2-4850-a6e3-204424239388)

Arc browser (chrome based)

### What browsers are you seeing the problem on?

Chrome (or chrome-based)

### Version

Current staging (no visible version number)

### Relevant log output

```Shell
No relevant logs :(
```

**Comment by taorepoara** [comment]
@Nesqwik Can you try it on the production server to see if the problem comes from the staging specificity or your environment (macOS) specificity ?

I can't reproduce it on my Linux Chromium.

**Comment by Nesqwik** [comment]
@taorepoara Same on production, same with firefox or arc browser (chrome based).
The green check is working but the error (red) character is not.
![Capture d’écran 2023-09-11 à 10 30 02](https://github.com/lenra-io/server/assets/6428498/016db146-50af-41ff-b4d1-74eca4faa225)

I don't know if it helps, but this is the "css computed" tab with the green check : 
![Capture d’écran 2023-09-11 à 10 32 14](https://github.com/lenra-io/server/assets/6428498/416d2154-130c-4bb5-bb46-c151d3413f99)

And this is the same tab with the red bugged character : 
![Capture d’écran 2023-09-11 à 10 32 20](https://github.com/lenra-io/server/assets/6428498/b1258a5d-6568-43af-99da-261e53b4d438)

As we can see, the "font-family" is the same in both case but in the bottom, the "Rendered Fonts" change from "Lucida Grande" for the green check, using the "local file" to "Source Sans Pro" using the "network file".

There is no font file in the "source" tab at all.

Maybe it uses a local font to display the icons that does not exist in MacOS ?

**Comment by taorepoara** [comment]
It seems to be specific to the macOS environment. Maybe the font file used is not up to date. I'll try to re-export it.
