### ISSUE TITLE
[Bug]: Cannot call webhooks endpoint (error 404)

### ISSUE THREAD

**Issue by jonas-martinez** [lenra-io/server#486]
### What happened?

It seems that we cannot call the `/app/webhooks` endpoint on the server as it always return a 404 error with no specific information as to where the error comes from. The route exists in the application_runner router so I guess this is either an error handling problem or a guard problem.

Example log I get from the devtool using my app :
```console
lenra-devtool-1  | 14:46:46.743 request_id=F42yDcGlyqP7aFAAAAGD [info] POST /app/webhooks
lenra-devtool-1  | 14:46:46.743 request_id=F42yDcGlyqP7aFAAAAGD [info] Sent 404 in 308µs
```

**Comment by taorepoara** [comment]
The webhook API endpoint changed to `/app-api/v1/webhooks`

**Comment by jonas-martinez** [comment]
As @taorepoara said, I was using the wrong API endpoint
